@startuml
package "nolang" {
    class Main {}
    class AlgebraicRunner {}
    class DynamicTypedRunner {}
    class StaticTypedRunner {}

}

package "nolang.common" {
    interface Type{
       + accepts(Value): boolean
    }
    record IntType
    record RealType
    record BoolType
    record VoidType

}
package "nolang.common.values" {
    interface Value {}
    interface NumericValue {}

    record IntValue
    record BoolValue
    record VoidValue
    record RealValue

}


package "nolang.common.core" {
    interface Either<L,R>{
        left()
        right()
        fold()
        isLeft()
        isRight()
        map()
        flatMap()
        orElse()
        orElseGet()
        leftOptional()
        rightOptional()
    }
    record Left
    record Right


    interface Eval{}
    record ExecutionContext

    interface EvalResult<A>
    record Returned
    record Interrupted

    interface InterruptReason{}
    record Control {
        + signal
    }
    record Error{
        + error
    }

    interface EvalControl{
    }
    record Break
    record Continue
    record Return

    EvalControl <|.. Break
    EvalControl <|.. Continue
    EvalControl <|.. Return

    interface EvalError{}
    record SyntaxError
    record ArithmeticError
    record TypeError
    record ArityError

    EvalError <|.. SyntaxError
    EvalError <|.. ArithmeticError
    EvalError <|.. TypeError
    EvalError <|.. ArityError

    record Scope

    record Function
    record FunctionSignature
    interface FunctionBody

    interface Declaration

    record Variable
    record Parameter
    record Function

    record FunctionRegistry{}

    interface ScopeError{}
    record UndefinedVariable
    record DuplicatedVariable
    record UninitializedVariable
    record UndefinedFunction

    class Arity{}



    enum Unit{}
}



package "nolang.common.combinators" {
    class BuiltInFunctions{
     + create(): Map<String, Function>
    }

    class Folds{
    +left(): NumericValue
    +right(): NumericValue
    +right(): NumericValue
    +foldLeftNumeric(): Eval<NumericValue>
    +foldLeftAssociativeNumeric(): Eval<NumericValue>
    +foldLeftDynamic(): Eval<Returned>
    +collectArguments(): Eval<List<Returned>>
    }
    class ScopeCombinators{}

    class ValueParser{
    +parseNumber(): Eval<NumericValue>
    +parseBoolean(): Eval<Value.BoolValue>
    }

    class NumericValues

    class ContextCombinators
    class ValueCombinators
    class EvalCombinators

}


package "nolang.common.operations" {
    interface "BinaryOperation<T>"{
    + operator(): String
    + apply(T left, T right): Eval<T>
    + {default} apply(Eval<T>left,Eval<T>right): Eval<T>
    }
    interface "RelationOperation<L, R>"
    {
    + operator(): String
    + apply(Eval<L> left, Eval<R> right): Eval<Value.BoolValue>
    + {default} apply(Eval<L> left, Eval<R> right): Eval<Value.BoolValue>
    }
    interface "UnaryOperation<T>" {
    + operator(): String
    + apply(T operand): Eval<T>
    + {default} apply(Eval<T>operand): Eval<T>
    }

    enum UnaryLogicalOperation{}
    enum UnaryNumericOperation{}
    enum NumericComparisonOperation{}
    enum BooleanComparisonOperation{}
    enum BinaryLogicalOperation{}
    enum BinaryNumericOperation{}
    class Logical{}
    class Numeric{}


}

package "nolang.algebraic" {
class AlgebraicEvalVisitor{}
class AlgebraicInterpreter{}
class AlgebraicSyntaxAnalyzer{}

}
    Type <|.. IntType
    Type <|.. RealType
    Type <|.. BoolType
    Type <|.. VoidType

    Type ..> Returned : uses
    BuiltInFunctions ..> Type : uses
    Declaration ..> Type : uses
    FunctionSignature ..> Type : uses

    EvalError <|-- ScopeError
    EvalError <|.. UndefinedFunction

    ScopeError <|.. UndefinedVariable
    ScopeError <|.. DuplicatedVariable
    ScopeError <|.. UninitializedVariable


    Either <|.. Left
    Either <|.. Right

    Scope ..> Either : returns
    Scope ..> Scope : uses
    Scope ..> ScopeError : uses
    Scope ..> Returned : uses

    FunctionRegistry ..> Eval : uses
    FunctionRegistry ..> FunctionSignature : uses
    FunctionRegistry ..> FunctionBody : uses
    FunctionRegistry ..> Scope : uses

    FunctionRegistry o-- Function
    Function --> FunctionSignature
    Function --> FunctionBody
    Function --> Scope
    Function ..> Eval : returns

    ExecutionContext ..> FunctionRegistry : uses
    ExecutionContext ..> Scope : uses

    Eval ..> EvalError : uses
    Eval ..> EvalControl : uses
    Eval ..> InterruptReason : uses
    Eval ..> ExecutionContext : uses
    Eval ..> EvalResult : returns

    EvalResult <|.. Returned
    EvalResult <|.. Interrupted

    Returned <|.. NumericValue
    Returned <|-- BoolValue
    Returned <|-- VoidValue


    Folds ..> NumericValues : uses
    BuiltInFunctions ..> ContextCombinators : uses
    BuiltInFunctions ..> Arity : uses
    BuiltInFunctions ..> FunctionParameter : uses
    ScopeCombinators ..> ContextCombinators : uses
    FunctionParameter ..> Returned : uses

    ContextCombinators ..> Eval : returns
    ContextCombinators ..> EvalResult : uses


    FunctionBody ..> Eval : returns
    ValueParser ..> Eval : returns
    ContextCombinators ..> Unit : returns
    ScopeCombinators ..> Eval : returns
    Folds ..> Eval : returns
    Folds ..> NumericValue : returns

    "UnaryOperation<T>" <|.. UnaryLogicalOperation : UnaryOperation<Value.BoolValue>
    "UnaryOperation<T>" <|.. UnaryNumericOperation : UnaryOperation<NumericValue>
    "RelationOperation<L, R>" <|.. NumericComparisonOperation : RelationOperation<NumericValue, NumericValue>
    "RelationOperation<L, R>" <|.. BooleanComparisonOperation : RelationOperation<Value.BoolValue, Value.BoolValue>
    "BinaryOperation<T>" <|.. BinaryLogicalOperation : BinaryOperation<Value.BoolValue>
    "BinaryOperation<T>" <|.. BinaryNumericOperation : BinaryOperation<NumericValue>

    UnaryLogicalOperation ..> Logical : uses
    UnaryNumericOperation ..> Numeric : uses
    NumericComparisonOperation ..> Numeric : uses

    BooleanComparisonOperation ..> RelationOperation : uses
    BooleanComparisonOperation ..> Eval : returns

    ValueCombinators ..> Eval : returns
    EvalCombinators ..> Eval : returns

    BinaryLogicalOperation ..> Logical : uses
    BinaryNumericOperation ..> Numeric : uses

    Logical ..> Eval : returns Eval<Value.BoolValue>
    Numeric ..> Eval : returns Eval<NumericValue>

    Value <|-- NumericValue
    Value <|-- BoolValue
    Value <|-- VoidValue

    NumericValue <|-- IntValue
    NumericValue <|-- RealValue

    FunctionSignature --> FunctionParameter : parameters
    FunctionSignature --> Arity : arity
    FunctionSignature --> Type : returnType

    Declaration <|.. Variable
    Declaration <|.. Parameter
    Declaration <|.. Function

    InterruptReason <|.. Error
    InterruptReason <|.. Control

    Declaration <|.. FunctionParameter

    AlgebraicEvalVisitor ..> ContextCombinators : uses

    AlgebraicRunner ..> BuiltInFunctions : uses
    AlgebraicRunner ..> AlgebraicInterpreter : uses
    AlgebraicRunner ..> EvalResult : returns


    AlgebraicInterpreter ..> AlgebraicSyntaxAnalyzer : uses
    AlgebraicInterpreter ..> EvalResult : returns

package "nolang.dynamic_typed" {
'planned
}
package "nolang.static_typed" {
'planned
}

@enduml
