@startuml
title Nolang - activity diagram

start
:Input;

:Main;
note right
select runner
end note

:Runner;
note right
creates Context
creates FunctionRegistry
end note

:Interpreter.evaluate(source, context);

:SyntaxAnalyzer.parse(source);
if (syntax error?) then (yes)
    :Eval.raiseError;
else (no)
    :EvalVisitor.visit(program);
    note right
    traverse AST -> construct deferred calculations
    end note
    :Eval.run(context);
end if

:Runner.handleResult(EvalResult);
if (result type?) then (Returned)
    :write stdout;
else (Interrupted)
    if (Interrupted type?) then (error)
        :write stderr;
    else (signal)
        :write stdout;
    end if
end if

stop
@enduml
